# Generated by Django 3.2.9 on 2021-11-13 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la compétence')),
                ('year', models.DateField(verbose_name='Année')),
                ('explain', models.TextField(verbose_name='Détails')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formationFields', models.CharField(max_length=255, verbose_name='Nom de la formation et diplome préparé ou obtenu')),
                ('formationYear', models.DateField(verbose_name='Année')),
                ('schoolName', models.CharField(max_length=255)),
                ('countryAndCity', models.CharField(max_length=255)),
                ('explain', models.TextField(blank=True, verbose_name='Détails')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('names', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Nom et prenom *')),
                ('competenceDomain', models.CharField(max_length=400, verbose_name='Domaine de compétence *')),
                ('mail', models.EmailField(max_length=254, verbose_name='Adresse mail *')),
                ('phone', models.CharField(max_length=20, verbose_name='numéro de téléphone *')),
                ('imageProfile', models.ImageField(blank=True, upload_to='', verbose_name='image de profile')),
                ('firstParagraph', models.TextField(blank=True, verbose_name="Mettez une petite phrase d'accroche")),
                ('wordsOfFirstParagraph', models.TextField(blank=True, verbose_name='Citez quelques outils ou logiciels que vous maitriser')),
                ('imageParagraph', models.ImageField(blank=True, upload_to='', verbose_name="image de la phrase d'accroche")),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la compétence')),
                ('year', models.DateField(verbose_name='Année')),
                ('explain', models.TextField(verbose_name='Détails')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPortfolio.userinfo', verbose_name='Auteur')),
            ],
        ),
    ]
