# Generated by Django 3.2.9 on 2021-11-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la compétence')),
                ('year', models.DateField(verbose_name='Année')),
                ('explain', models.TextField(verbose_name='Détails')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la compétence')),
                ('year', models.DateField(verbose_name='Année')),
                ('explain', models.TextField(verbose_name='Détails')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formationFields', models.CharField(max_length=255, verbose_name='Nom de la formation et diplome préparé ou obtenu')),
                ('formationYear', models.DateField(verbose_name='Année')),
                ('schoolName', models.CharField(max_length=255)),
                ('countryAndCity', models.CharField(max_length=255)),
                ('explain', models.TextField(blank=True, verbose_name='Détails')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('names', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Titre de la compétence')),
                ('competenceDomain', models.CharField(max_length=400, verbose_name='Année')),
                ('mail', models.EmailField(max_length=254, verbose_name='EMail')),
                ('phone', models.CharField(max_length=20, verbose_name='EMail')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
            ],
        ),
    ]
