# Generated by Django 3.2.9 on 2021-11-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='competenceDomain',
            field=models.CharField(max_length=400, verbose_name='Domaine de compétence'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='names',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Nom et prenom'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='numéro de téléphone'),
        ),
    ]
